### ISSUE TITLE
Erroneous rucio download summary info

### ISSUE THREAD

**Issue by cohm** [rucio/rucio#1512]
Motivation
----------

I tried to download one file from a dataset, and the output from rucio doesn't make sense:

```
lxplus040:/tmp/cohm > rucio get --nrandom 1 data17_5TeV:data17_5TeV.00340634.calibration_PixelBeam.merge.DAOD_IDPIXLUMI.c1166_m1905
----------------------------------
Download summary
----------------------------------------
DID data17_5TeV:data17_5TeV.00340634.calibration_PixelBeam.merge.DAOD_IDPIXLUMI.c1166_m1905
Total files :                                 0
Downloaded files :                            0
Files already found locally :                 0
Files that cannot be downloaded :             0
```

Nothing was downloaded, so it should somehow say that there was a problem somewhere in the output. Could this be improved?

Thanks a lot!

Best,
Christian

Modification
------------

**Comment by TWAtGH** [comment]
This dataset is only available at `CERN-PROD_DERIVED` which has the `istape` attribute set to `True`. Download is not allowed from tape endpoints by non-admin accounts.
Because of this no file is considered for download. Anyway this is probably already fixed with 1.17. Needs to be checked though.

**Comment by cohm** [comment]
Thanks for the quick reply! 

Yes, I should have said that I figured out this much myself as well. I think the output is still wrong and should be fixed.

Best,
Christian

**Comment by TWAtGH** [comment]
With 1.17 this case is checked and the `NoFilesDownloaded` exception is thrown. The CLI exit with a return code != 0. There is no error message though.

**Comment by bari12** [comment]
@TWAtGH Can you add an error message for this case?

**Comment by TWAtGH** [comment]
Yes I'm currently working on the downloadclient anyway
