### ISSUE TITLE
[dev container] tests fail on authentication

### ISSUE THREAD

**Issue by ygrange** [rucio/rucio#2731]
Motivation
----------
I'm trying to setup the dev container locally using the default docker-compose and run the tests. When I do that, it fails with the message: 

```
Sync rse_repository
cannot get auth_token
Traceback (most recent call last):
  File "tools/sync_rses.py", line 34, in <module>
    c = Client()
  File "/usr/lib/python2.7/site-packages/rucio/client/client.py", line 64, in __init__
    super(Client, self).__init__(rucio_host=rucio_host, auth_host=auth_host, account=account, ca_cert=ca_cert, auth_type=auth_type, creds=creds, timeout=timeout, user_agent=user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/accountclient.py", line 44, in __init__
    super(AccountClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/accountlimitclient.py", line 40, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/metaclient.py", line 45, in __init__
    super(MetaClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/pingclient.py", line 35, in __init__
    super(PingClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 45, in __init__
    super(ReplicaClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/requestclient.py", line 37, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/rseclient.py", line 47, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/scopeclient.py", line 46, in __init__
    super(ScopeClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/didclient.py", line 56, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 39, in __init__
    super(RuleClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, dq2_wrapper)
  File "/usr/lib/python2.7/site-packages/rucio/client/subscriptionclient.py", line 38, in __init__
    super(SubscriptionClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/lockclient.py", line 44, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/configclient.py", line 44, in __init__
    super(ConfigClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/touchclient.py", line 41, in __init__
    super(TouchClient, self).__init__(rucio_host, auth_host, account, ca_cert, auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/importclient.py", line 36, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/exportclient.py", line 35, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/credentialclient.py", line 35, in __init__
    auth_type, creds, timeout, user_agent)
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 227, in __init__
    self.__authenticate()
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 642, in __authenticate
    self.__get_token()
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 550, in __get_token
    raise CannotAuthenticate('userpass authentication failed')
rucio.common.exception.CannotAuthenticate: Cannot authenticate.
Details: userpass authentication failed
Failed to sync!
```
This may be a comparable issue to #1156, but that seems to have been solved months ago, so I am not really sure what to do here. Also, I think the tests will anyhow fail when one copies the instructions from the manual instructions on the documentation page (https://rucio.readthedocs.io/en/latest/developing.html?highlight=development) since that one actually sets the db, user and password to rucio while the tests assume mysql, root and secret respectively. 

Modification
------------
Either fix the test or the setup so that the authentication works in the test of the dev container. Or tell me what I could be doing better.

**Comment by hahahannes** [comment]
Hi, can you maybe check if there is some exception output in /var/log/rucio/httpd_error_log.
Also try to rebuild the Docker image. I had the same problem when I build it on the next branch and then changed to another branch based on master where some dependency was missing.

**Comment by ygrange** [comment]
```
[Mon Jul 15 09:32:09.172307 2019] [:error] [pid 6] [client 127.0.0.1:55116] mod_wsgi (pid=6): Target WSGI script '/opt/rucio/lib/rucio/web/rest/authentication.py' cannot be loaded as Python module.
[Mon Jul 15 09:32:09.172346 2019] [:error] [pid 6] [client 127.0.0.1:55116] mod_wsgi (pid=6): Exception occurred processing WSGI script '/opt/rucio/lib/rucio/web/rest/authentication.py'.
[Mon Jul 15 09:32:09.172380 2019] [:error] [pid 6] [client 127.0.0.1:55116] Traceback (most recent call last):
[Mon Jul 15 09:32:09.172406 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/opt/rucio/lib/rucio/web/rest/authentication.py", line 36, in <module>
[Mon Jul 15 09:32:09.172746 2019] [:error] [pid 6] [client 127.0.0.1:55116]     from rucio.api.authentication import (get_auth_token_user_pass,
[Mon Jul 15 09:32:09.172771 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/api/authentication.py", line 22, in <module>
[Mon Jul 15 09:32:09.172981 2019] [:error] [pid 6] [client 127.0.0.1:55116]     from rucio.api import permission
[Mon Jul 15 09:32:09.173002 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/api/permission.py", line 17, in <module>
[Mon Jul 15 09:32:09.173110 2019] [:error] [pid 6] [client 127.0.0.1:55116]     from rucio.core import permission
[Mon Jul 15 09:32:09.173130 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/permission/__init__.py", line 38, in <module>
[Mon Jul 15 09:32:09.173266 2019] [:error] [pid 6] [client 127.0.0.1:55116]     from .atlas import *  # NOQA pylint:disable=wildcard-import
[Mon Jul 15 09:32:09.173287 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/permission/atlas.py", line 25, in <module>
[Mon Jul 15 09:32:09.173896 2019] [:error] [pid 6] [client 127.0.0.1:55116]     import rucio.core.did
[Mon Jul 15 09:32:09.173942 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/did.py", line 46, in <module>
[Mon Jul 15 09:32:09.175187 2019] [:error] [pid 6] [client 127.0.0.1:55116]     import rucio.core.rule
[Mon Jul 15 09:32:09.175208 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/rule.py", line 52, in <module>
[Mon Jul 15 09:32:09.177980 2019] [:error] [pid 6] [client 127.0.0.1:55116]     import rucio.core.replica  # import get_and_lock_file_replicas, get_and_lock_file_replicas_for_dataset
[Mon Jul 15 09:32:09.178005 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/replica.py", line 54, in <module>
[Mon Jul 15 09:32:09.179967 2019] [:error] [pid 6] [client 127.0.0.1:55116]     from rucio.core.credential import get_signed_url
[Mon Jul 15 09:32:09.180003 2019] [:error] [pid 6] [client 127.0.0.1:55116]   File "/usr/lib/python2.7/site-packages/rucio/core/credential.py", line 43, in <module>
[Mon Jul 15 09:32:09.180205 2019] [:error] [pid 6] [client 127.0.0.1:55116]     import boto3
[Mon Jul 15 09:32:09.180233 2019] [:error] [pid 6] [client 127.0.0.1:55116] ImportError: No module named boto3
[Mon Jul 15 09:32:09.181110 2019] [ssl:debug] [pid 6] ssl_engine_io.c(993): [client 127.0.0.1:55116] AH02001: Connection closed to child 0 with standard shutdown (server localhost:443)
```

So I pip-installed it and it runs through. It is still running so I can't report it to go through to the end yet, but the first issue seems to be tackled by the extra pip install inside the container (FYI: I run the container using docker-compose which basically pulls it from docker hub; I haven't tested building it using the Dockerfile in the dev subdirectory).

**Comment by ygrange** [comment]
Cheered a bit too soon. I think one of the last tests seems to fail as well. 
```
======================================================================
ERROR: REPLICA RECOVERER: Testing declaration of suspicious replicas as bad if they are found available on other RSEs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/opt/rucio/lib/rucio/tests/test_replica_recoverer.py", line 51, in setUp
    assert_true(exitcode == 0)
AssertionError: False is not true

======================================================================
FAIL: REAPER (DAEMON): Test the reaper daemon.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/rucio/lib/rucio/tests/test_reaper.py", line 47, in test_reaper
    nose.tools.assert_equal(exitcode, 0)
AssertionError: 127 != 0
-------------------- >> begin captured stdout << ---------------------
('rucio-reaper --run-once --rses MOCK', '', '/bin/sh: rucio-reaper: command not found\n')

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: main: starting processes
root: INFO: Reaper: This instance will work on RSEs: MOCK
root: INFO: Starting Reaper: Worker 0, child 1 will work on RSEs: MOCK
root: INFO: Reaper 0-1: Running on RSE MOCK None
root: DEBUG: RSE: MOCK, source_for_total_space: storage, source_for_used_space: storage
root: INFO: Reaper 0-1: Space usage for RSE {'rse_type': DISK, 'region_code': None, 'ASN': None, 'city': None, 'ISP': u'Brookhaven National Laboratory', 'rse': u'MOCK', 'created_at': datetime.datetime(2019, 7, 15, 9, 44, 3), 'deterministic': True, 'availability': 7L, 'time_zone': None, 'longitude': None, 'continent': u'NA', 'updated_at': datetime.datetime(2019, 7, 15, 9, 44, 3), 'staging_area': False, 'volatile': False, 'deleted': False, 'country_name': u'United States', 'latitude': None, 'deleted_at': None, 'id': 'd7c8e037e0a64b46b537a3ba57836b68'} - max_being_deleted_files: 10, needed_free_space: None, used: None, free: None
root: INFO: Reaper 0-1: free space is above minimum limit for MOCK
root: DEBUG: Reaper 0-1: list_unlocked_replicas on MOCK for 0 bytes in 0.03817486763 seconds: 0 replicas
root: INFO: Reaper 0-1: No replicas to delete MOCK. The next check will occur at 2019-07-15 10:41:03.842946
root: INFO: Graceful stop requested
root: INFO: Graceful stop done
--------------------- >> end captured logging << ---------------------
```
Seems like rucio-reaper doesn't exist in this version.

**Comment by ygrange** [comment]
Confirming that using a dev container built from the repository itself solves the first issue. So adding the build instructions to the documentation, or pushing a new dev container to docker hub would fix that one.
Second (reaper) issue is still there.

**Comment by hahahannes** [comment]
Yes, the new docker image should be already pushed. I will have a look for the reaper issue

**Comment by ygrange** [comment]
Now it complains that
```
Sync rse_repository
Traceback (most recent call last):
  File "tools/sync_rses.py", line 30, in <module>
    json_data = open(rse_repo_file)
IOError: [Errno 2] No such file or directory: 'etc/rse_repository.json'
Failed to sync!
```
Probably I can fix it by linking /etc in in the docker-compose, but I don't know if that's the intention.

**Comment by tbeerman** [comment]
Sorry, I moved the dev container config to our container repository to setup automated builds on docker hub but I forgot this file. Should be fixed now if you pull again from docker hub.

**Comment by hahahannes** [comment]
@ygrange Does it work for you?

**Comment by ygrange** [comment]
I’m on leave now. Will have a look at it early next week!

--
Y. Grange

> Op 25 jul. 2019 om 16:00 heeft Hannes Hansen
<notifications@github.com> het volgende geschreven:

**Comment by ygrange** [comment]
Still can't find `reaper`. I decided to updte the checked out version to 1.20.3 and I get another bunch of errors looking line this:
```
======================================================================
FAIL: SCOPE (REST): send a POST to create a already existing scope to test the error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/rucio/lib/rucio/tests/test_scope.py", line 98, in test_scope_duplicate
    assert_equal(res1.status, 200)
AssertionError: 500 != 200
-------------------- >> begin captured stdout << ---------------------
```

**Comment by bari12** [comment]
I think the `reaper` error is related to it not having a `bin/` script like the other daemons. For the reaper we tried to build this on install of the package, which might not happen like this in the container. (We probably should go back to bin scripts)

**Comment by mlassnig** [comment]
https://github.com/rucio/rucio/pull/2773 just passed and ready for merge, this fixes the reaper issue
